plugins {
    id 'java'
    id 'application'
}

group = 'com.inventario'
version = '1.0.0'

repositories { mavenCentral() }

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType(Test) {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
        exceptionFormat "full"
        showStandardStreams = true
    }
}

application {
    // Arranque del servidor HTTP embebido
    mainClass = 'com.inventario.web.WebServer'
}

jar {
    manifest {
        attributes 'Main-Class': application.mainClass
    }
}
